### ISSUE TITLE
Missing libraries in 5.4.0 version of plugin

### ISSUE THREAD

**Issue by arjansh** [datacleaner/pdi-datacleaner#42]
When I try to build a profiling job in DataCleaner from Spoon by selecting the "Build your own profiling job" sub-menu under the "Profile with DataCleaner" option in the context menu in Spoon, I get this stacktrace:

```Failed to load DataCleaner plugin class: Could not initialize class org.datacleaner.util.convert.StringConverter
java.lang.NoClassDefFoundError: Could not initialize class org.datacleaner.util.convert.StringConverter
	at org.datacleaner.job.JaxbJobWriter.addConfiguration(JaxbJobWriter.java:294)
	at org.datacleaner.job.JaxbJobWriter.configureJobType(JaxbJobWriter.java:239)
	at org.datacleaner.job.JaxbJobWriter.configureJobType(JaxbJobWriter.java:162)
	at org.datacleaner.job.JaxbJobWriter.write(JaxbJobWriter.java:148)
	at org.pentaho.di.profiling.datacleaner.ModelerHelper.profileStep(ModelerHelper.java:416)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:305)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:290)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:545)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:490)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:402)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1366)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:8022)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9277)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:692)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
```
This is most likely caused by the fact that the 5.4.0 version of the plugin only contains the MetaModel-core-5.0.1.jar and not the other MetaModel jars, like MetaModel-csv-5.0.1.jar, which older versions of the plugin did contain.

**Comment by diogoff** [comment]
I have the same problem. Same stack trace as @arjansh and also this one:

```
java.lang.NoClassDefFoundError: org/apache/metamodel/csv/CsvConfiguration
    at org.datacleaner.util.convert.MapStringToStringConverter.<init>(MapStringToStringConverter.java:42)
    at org.datacleaner.util.convert.DelegatingConverter.<init>(DelegatingConverter.java:62)
    at org.datacleaner.util.convert.DelegatingConverter.<init>(DelegatingConverter.java:55)
    at org.datacleaner.util.convert.StringConverter.createBaseConverter(StringConverter.java:128)
    at org.datacleaner.util.convert.StringConverter.<init>(StringConverter.java:87)
    at org.datacleaner.util.convert.StringConverter.<clinit>(StringConverter.java:70)
    at org.datacleaner.job.JaxbJobWriter.addConfiguration(JaxbJobWriter.java:294)
    at org.datacleaner.job.JaxbJobWriter.configureJobType(JaxbJobWriter.java:239)
    at org.datacleaner.job.JaxbJobWriter.configureJobType(JaxbJobWriter.java:162)
    at org.datacleaner.job.JaxbJobWriter.write(JaxbJobWriter.java:148)
    at org.pentaho.di.profiling.datacleaner.ModelerHelper.profileStep(ModelerHelper.java:416)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:305)
    at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:290)
    at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
    at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
    at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
    at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:545)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:490)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:402)
    at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
    at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1366)
    at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:8022)
    at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9277)
    at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:692)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.metamodel.csv.CsvConfiguration
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
    at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 38 more
```

So I reached the same conclusion, that the current plugin version 5.4.0 is missing MetaModel-csv-5.0.1.jar and so on.

To see if I could fix it, I grabbed the JARs from [here](https://archive.apache.org/dist/metamodel/metamodel-5.0.1/packaged/) and unzipped them to data-integration/plugins/pdi-datacleaner/lib.

However, this did not fix the problem, as another exception was thrown (something like `NoSuchMethodError` on `org.apache.metamodel.QueryPostprocessDataContext.<init>`).

I looked at a previous version of the plugin that I had on an old VM, and I noticed it was using metamodel-4.4.0.

So at this stage I'm not sure if the plugin is missing the metamodel-5.0.1 JARs or if has the wrong version of metamodel altogether.

**Comment by diogoff** [comment]
I solved this problem by copying all JARs from DataCleaner/lib to data-integration/plugins/pdi-datacleaner/lib.
(Note that I've used DataCleaner 5.4.0, in order to avoid any version mismatch.)

**Comment by aroberts394** [comment]
@diogoff that worked for me! 
Although I'm getting a weird formatting issue with the tables. They tables are overlapping each other (see picture). 
![image](https://user-images.githubusercontent.com/12590113/91254892-19c15f00-e729-11ea-8d43-8e631b98ba84.png)

Do you have similar issue?

**Comment by diogoff** [comment]
No. Could this be Java-related? Which Java version are you using?

**Comment by aroberts394** [comment]
> No. Could this be Java-related? Which Java version are you using?

Not sure. I'm using java version "1.8.0_261"

**Comment by diogoff** [comment]
Rather than copying JAR files, a nicer way to solve this is to edit `data-integration/launcher/launcher.properties` and append the location of `DataCleaner/lib` to the end of libraries, e.g.:
`libraries=../test:../lib:../libswt:../../DataCleaner/lib`
