### ISSUE TITLE
plugin doesn't work for Pentaho pdi-ce-7.1.0.0-12  

### ISSUE THREAD

**Issue by eccoilmoro** [datacleaner/pdi-datacleaner#45]
Environment : Windows 10 - pdi-ce-7.1.0.0-12  - Data Cleaner Plugin 5.4.0 - Data Cleaner 5.1.5

When starting plugin from PDI the following error is raised 
Failed to load DataCleaner plugin class: org/apache/metamodel/csv/CsvConfiguration
java.lang.NoClassDefFoundError: org/apache/metamodel/csv/CsvConfiguration
	at org.datacleaner.util.convert.MapStringToStringConverter.<init>(MapStringToStringConverter.java:42)
	at org.datacleaner.util.convert.DelegatingConverter.<init>(DelegatingConverter.java:62)
	at org.datacleaner.util.convert.DelegatingConverter.<init>(DelegatingConverter.java:55)
	at org.datacleaner.util.convert.StringConverter.createBaseConverter(StringConverter.java:128)
	at org.datacleaner.util.convert.StringConverter.<init>(StringConverter.java:87)
	at org.datacleaner.util.convert.StringConverter.<clinit>(StringConverter.java:70)
	at org.datacleaner.job.JaxbJobWriter.addConfiguration(JaxbJobWriter.java:294)
	at org.datacleaner.job.JaxbJobWriter.configureJobType(JaxbJobWriter.java:239)
	at org.datacleaner.job.JaxbJobWriter.configureJobType(JaxbJobWriter.java:162)
	at org.datacleaner.job.JaxbJobWriter.write(JaxbJobWriter.java:148)
	at org.pentaho.di.profiling.datacleaner.ModelerHelper.profileStep(ModelerHelper.java:416)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:305)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:290)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)

Then i put MetaModel-csv-5.0.1.jar in the libs and the previous error is not raised anymore.
But I get this error now :
 

Message:
    java.lang.NoSuchMethodError: org.apache.metamodel.QueryPostprocessDataContext.<init>(Z)V
Level:
    SEVERE
Stack Trace:
org.apache.metamodel.QueryPostprocessDataContext. (Z)V
    org.pentaho.di.profiling.datacleaner.KettleDataContext.<init>(KettleDataContext.java:56)
    org.pentaho.di.profiling.datacleaner.KettleDatastore.createDatastoreConnection(KettleDatastore.java:47)
    org.datacleaner.connection.UsageAwareDatastore.getDatastoreConnection(UsageAwareDatastore.java:117)
    org.datacleaner.connection.UsageAwareDatastore.openConnection(UsageAwareDatastore.java:128)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:436)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:409)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:329)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:308)
    org.datacleaner.actions.OpenAnalysisJobActionListener.openAnalysisJob(OpenAnalysisJobActionListener.java:188)
    org.datacleaner.actions.OpenAnalysisJobActionListener.open(OpenAnalysisJobActionListener.java:115)
    org.datacleaner.bootstrap.Bootstrap.runInternal(Bootstrap.java:206)
    org.datacleaner.bootstrap.Bootstrap.run(Bootstrap.java:102)
    org.datacleaner.Main.main(Main.java:60)
    org.datacleaner.Main.main(Main.java:46)

**Comment by diogoff** [comment]
I think this is another instance of #42 
See the workaround I proposed: https://github.com/datacleaner/pdi-datacleaner/issues/42#issuecomment-670181513
